#!/usr/bin/python

import pwd
import sys
import os
import subprocess

uid = os.getuid()
name, _, _ = pwd.getpwuid(uid).pw_gecos.partition(',')

for r in sys.argv[1:]:
    subprocess.check_call(['svn', 'ps', 'svn:author', name, '--revprop', '-r', r])

# vim:ts=4 sw=4 et
