#!/usr/bin/python
# encoding=UTF-8

# Copyright © 2009-2018 Jakub Wilk <jwilk@jwilk.net>
# SPDX-License-Identifier: MIT

import pwd
import sys
import os
import subprocess

uid = os.getuid()
name, _, _ = pwd.getpwuid(uid).pw_gecos.partition(',')

for r in sys.argv[1:]:
    subprocess.check_call(['svn', 'ps', 'svn:author', name, '--revprop', '-r', r])

# vim:ts=4 sw=4 et
