#!/usr/bin/python

import os
import sys

def parse_args(args):
    args = iter(args)
    args.next()
    while True:
        arg = args.next()
        if arg == '-u':
            continue
        if arg == '-L':
            args.next()
            continue
        yield arg

executable = '/usr/bin/wdiff'
new_args = [executable]
new_args += parse_args(sys.argv)
os.execv(executable, new_args)

# vim:ts=4 sw=4 et
